---
name: Update Docker Hub information

on:
  release:
    types: [published]
  push:
    branches:
      - main
    paths:
      - DOCKER.md
      - .github/workflows/dockerhub.yaml

env:
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME || github.repository_owner }}
  DOCKERHUB_REPOSITORY: ${{ vars.DOCKERHUB_REPOSITORY || github.event.repository.name }}

permissions: read-all

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Sync information on Docker Hub
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}
          readme-filepath: ./DOCKER.md
